.travis.yml, README.md, requirements.txt
=> python3 support

tests/test_backup.py
Added asserts for the actual backup contents to backup tests
fixes #9 
Test result:
```
pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_backup.py
====================================== test session starts =======================================
ansible: 2.6.3
collected 18 items                                                                               
tests/test_backup.py ..................                                                    [100%]
================================== 18 passed in 2635.85 seconds ==================================
```
=> check backup files

tests/test_restore.py
The last debt from robottelo, takes longer but I think it's worth it to check restore from offline files, as that is the recommended backup mode.
test:
```
pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_restore.py::test_positive_restore_offline_backup
============================================= test session starts ==============================================
ansible: 2.6.3
collected 1 item                                                                                               
tests/test_restore.py . …
```
=> restore from offline backup files

testfm/helpers.py, tests/test_backup.py, tests/test_service.py
Fixes #18 
Fixes #17 
Fixes #16
=> Added coverage for bugzillas

tests/test_health.py
Fixes issue #52 
Test Result: 
```
$ pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_health.py -k "test_positive_puppet_check_empty_cert_requests or test_positive_puppet_check_no_empty_cert_requests" -svvv
collected 13 items / 11 deselected                                                                                                                                     
tests/test_health.py::test_positive_puppet_check_no_empty_cert_requests 2019-03-28 16:07:03,356 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario …
```
=> add coverage around "remove empty puppet cacert request files"

tests/test_advanced.py
Fixes issue #51 
Test Result:
```
$ pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_advanced.py -k test_positive_sync_plan_disable_enable -svvv
platform linux -- Python 3.6.4, pytest-3.6.1, py-1.6.0, pluggy-0.6.0 -- /home/jpathan/projects/testfm/env2/bin/python
ansible: 2.6.3
plugins: services-1.2.1, mock-1.6.3, ansible-2.0.1
collected 15 items / 14 deselected …
```
=> add test coverage around sync plan enable/disable

requirements.txt
=> stay with ansible 2.6

tests/conftest.py, tests/test_advanced.py
=> fixes test_positive_sync_plan_disable_enable

tests/conftest.py, tests/test_health.py
Fixes issue #66 
Test Results:
```
$ pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_yum_exclude_list -svvv
collected 15 items / 13 deselected                                                                                                                                                        
tests/test_health.py::test_positive_check_yum_exclude_list 2019-05-31 12:11:17,198 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario
================================================================== …
```
=> added check_yum_exclude_list check

testfm/packages.py, tests/conftest.py, tests/test_packages.py
=> tests for version-locking features. Fixes issue #69

testfm/decorators.py, testfm/helpers.py, tests/test_health.py, tests/test_packages.py
=> Fixes issue #84

testfm/constants.py, testfm/decorators.py, testfm/helpers.py, tests/conftest.py, tests/test_advanced.py, tests/test_upgrade.py
=> fixes issue #86 and issue #79

tests/conftest.py, tests/test_health.py
=> fixes #83 - Fix test_health.test_negative_check_hammer_ping for FM > v0.4.3

testfm/constants.py, tests/conftest.py, tests/test_health.py, tests/test_packages.py
=> Fixes #103 - Add automation for check-epel-repository check.

.travis.yml, Makefile, requirements.txt, scripts/fix_uuids.sh, testimony.yaml, tests/test_advanced.py, tests/test_backup.py, tests/test_health.py, tests/test_maintenance_mode.py, tests/test_packages.py
=> Fixes #102 - Add uuid checking mechanism for Testfm similar to one present in Robottelo."

tests/conftest.py, tests/test_health.py
=> Correct test case for BZ 1632768

tests/conftest.py, tests/test_advanced.py
=> Fixes #92 - fix test_positive_beta_repositories

tests/test_health.py
Fixes #87 
Test result:
```
$ pytest --ansible-host-pattern server --ansible-user=root --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_tmout_variable 
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.8.0, pluggy-0.6.0
ansible: 2.6.14
collected 21 items / 20 deselected                                                                                                                                                        
tests/test_health.py . …
```
=> Fixes #87 - Add tests around TMOUT environment variable.

testfm/constants.py, tests/conftest.py, tests/test_advanced.py, tests/test_health.py, tests/test_upgrade.py
=> fix fma for Satellite 6.7

testfm/decorators.py, testfm/helpers.py, tests/test_backup.py
=> Add helper server to find server is satellite or capsule

tests/conftest.py, tests/test_backup.py
=> Fixes #143 - Setup and teardown for backup tests.

tests/conftest.py, tests/test_packages.py
See FMA job 79 for test result.
=> Fixes test_positive_fm_packages_install

tests/test_service.py
```
platform linux -- Python 3.6.8, pytest-3.6.1, py-1.8.0, pluggy-0.6.0 -- /home/jpathan/projects/env-testfm/bin/python3
collecting ... collected 10 items / 9 deselected
tests/test_service.py::test_positive_stop_foreman_service 2020-11-24 18:16:40,719 - testfm.log - INFO - {'changed': True, 'end': '2020-11-24 18:16:40.498167', 'stdout': 'Running Status 
PASSED
=================== 1 passed, 9 deselected in 123.91 seconds ===================
```
=> added the test for foreman service

tests/conftest.py, tests/test_health.py
=> Fixes #183 - Add test for validate_yum_config check

testfm/decorators.py, tests/test_advanced.py, tests/test_backup.py, tests/test_health.py, tests/test_packages.py, tests/test_restore.py, tests/test_service.py, tests/test_upgrade.py
=> Fix Capsule marks to use direct pytest marks and remove capsule_only

tests/test_health.py
**Description:**
1. Update test_positive_remove_job_file to cover BZ-1827219.
2. This test gets to hang in CI for pytest not getting `--assumeyes` to confirm to install package needed for disk-performance check.
```
$ pytest -sv --disable-warnings --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_remove_job_file 
========================================================== test session starts ==========================================================
platform linux -- Python 3.7.7, pytest-3.6.1, py-1.10.0, pluggy-0.6.0 -- /home/gtalreja/sat_workspace/testfm/.testfm/bin/python
plugins: ansible-2.2.4 …
```
=> Update test_positive_remove_job_file to cover BZ-1827219

testfm/constants.py, testfm/helpers.py, tests/test_advanced.py, tests/test_health.py, tests/test_upgrade.py
=> Fix FMA for Satellite 6.10

.github/workflows/merge_to_master.yml, .github/workflows/pull_request.yml, Dockerfile
=> Add workflow for updating testfm image on quay

.github/workflows/merge_to_master.yml
=> Update quay image tag in GHA to testfm

tests/conftest.py, tests/test_advanced.py
=> Add check for BZ-1830355

testfm/packages.py, tests/conftest.py, tests/test_packages.py
**Satellite:**
```
$ pytest -v --ansible-host-pattern server --ansible-user=root --ansible-inventory testfm/inventory tests/test_packages.py -k test_positive_packages_check_update
=============================================== test session starts ===========================================================
collected 4 items / 3 deselected …
```
=> Add test for packages check-update check

tests/conftest.py, tests/test_health.py, tests/test_packages.py, tests/test_service.py
```
1] test_service.py
$ pytest -v --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_service.py -k test_positive_service_status_rpmsave
============================================ test session starts ====================================================
collected 12 items / 11 deselected …
```
=> Add test for BZ-1945916, BZ-1894149 and add manual tests 

.github/workflows/merge_to_master.yml, .github/workflows/pull_request.yml
=> Fix GHA push to master, run GHA against Py3.8 and Py3.9

tests/test_upgrade.py
=> Fix upgrade list test for 7.0

testfm/constants.py
=> Update repositories constants for 7.0

tests/conftest.py
=> [6.10.z] Change pip installation method for setup_install_pexpect

testfm/helpers.py, tests/conftest.py
**`Test Results:`**
```
$ pytest -v --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_hotfix_installed
========================================= test session starts ===========================================================
collected 27 items / 25 deselected …
```
=> [6.9.z]Fix hotfix tests

testfm/constants.py, tests/test_advanced.py
**Tests Results:**
**RHEL7:**
```
(.testfm) [gtalreja@gtalreja testfm]$ pytest -q --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_advanced.py -k test_positive_satellite_repositories_setup
.                                                                                                                                 [100%]
1 passed, 13 deselected in 879.67 seconds
```
```
(.testfm) [gtalreja@gtalreja testfm]$ pytest -q --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_advanced.py -k test_positive_capsule_repositories_setup
.                                                                                                                                 [100%]
1 passed, 13 deselected in 909.38 …
```
=> Update satellite and capsule repo constants for el8

testfm/constants.py, tests/test_advanced.py, tests/test_upgrade.py
=> Update Sat7.0 references to 6.11

.pre-commit-config.yaml
=> Update pre-commit hooks to latest

.github/workflows/merge_to_611z.yml, testfm/constants.py, tests/test_advanced.py
=> [6.11.z] Update version specific details for 6.11

testfm/constants.py, tests/conftest.py, tests/test_advanced.py, tests/test_maintenance_mode.py, tests/test_upgrade.py
=> Update version specific details and tests for 6.12

.github/dependabot.yml
Dependabot configuration file for PRs to bump the requirements for both python and GHA.
=> Dependabot Configuration YAML
