- requirements.txt
- tests/test_backup.py
added some negative tests for f-m backup
```
pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_backup.py::test_negative_backup_online_incremental_nodir
============================================== test session starts ==============================================
platform linux2 -- Python 2.7.15, pytest-3.4.0, py-1.5.3, pluggy-0.6.0
ansible: 2.3.2.0
plugins: ansible-1.3.1
collected 1 item                                                                                                
tests/test_backup.py .                                                                                    [100%]
=========================================== 1 passed in 8.47 seconds …
```
> negative tests for f-m backup

- testfm/base.py
- tests/test_restore.py
fixes #10 
Test results, tried with p3:
```
pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_restore.py::test_positive_restore_online_backup
========================================= test session starts ==========================================
ansible: 2.6.3
collected 1 item                                                                                       
tests/test_restore.py .                                                                          [100%]
====================================== 1 passed in 950.56 seconds ======================================
pytest …
```
> restore test fix and negative tests

- tests/test_backup.py
fixes #8 
source dir for incremental backup is now correctly specified, also added a comparison for backup dirs
results:
```
pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_backup.py -k incremental
=============================================== test session starts ================================================
ansible: 2.6.3
collected 18 items / 15 deselected                                                                                 
tests/test_backup.py ...                                                                                     [100%] …
```
> incremental backup source dir

- testfm/decorators.py
- tests/test_backup.py
fixes #22 
result:
```
pytest --ansible-host-pattern capsule --ansible-user=root  --ansible-inventory testfm/inventory tests/test_backup.py 
=============================================== test session starts ================================================
ansible: 2.6.3
collected 18 items                                                                                                 
tests/test_backup.py ..................                                                                      [100%]
=========================================== 18 passed in 1909.28 seconds ===========================================
```
> fix content check for capsule variant

- testfm/constants.py
- tests/test_health.py
Test result:
```
$ pytest --ansible-host-pattern satellite --ansible-user=root --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_upstream_repository -svvv
collected 9 items / 8 deselected                                                                                                                                       
tests/test_health.py::test_positive_check_upstream_repository 2018-11-06 16:15:12,606 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario
================================================================================
Check if any upstream repositories …
```
> automated "check-upstream-repository" check

- tests/test_health.py
Fixes #40 
Test Result:
```
$ pytest --ansible-host-pattern satellite --ansible-user=root --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_available_space -svvv
collected 10 items / 9 deselected                                                                                                                                      
tests/test_health.py::test_positive_available_space 2018-11-13 19:21:26,081 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario
================================================================================
Check to make sure root(/) partition has …
```
> automated "foreman-maintain health check --label available-space"

- tests/test_advanced.py
Fixes issue #47 
Fixes test_positive_foreman_tasks_ui_investigate and test_positive_foreman_maintain_hammer_setup 
Test Result:
```
$ pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_advanced.py -k test_positive_foreman_tasks_ui_investigate 
collected 15 items / 14 deselected                                                                                                                                     
tests/test_advanced.py . …
```
> Fixes test_positive_foreman_maintain_hammer_setup and test_positive_foreman_tasks_ui_investigate

- tests/conftest.py
- tests/test_upgrade.py
Fixes issue #75
Test Result:
```
$ pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_upgrade.py -k test_positive_foreman_maintain_upgrade_list 
collected 1 item                                                                                                                                                                          
tests/test_upgrade.py .                                                                                                                                                             [100%] …
```
> fixes test_positive_foreman_maintain_upgrade_list

- tests/test_upgrade.py
Fixes #111 
```
$ pytest --ansible-host-pattern satellite --ansible-user=root --ansible-inventory testfm/inventory tests/test_upgrade.py -k test_positive_repositories_validate
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.8.0, pluggy-0.6.0
ansible: 2.6.14
collected 2 items / 1 deselected                                                                                                                                                          
tests/test_upgrade.py . …
```
> Fixes #111 - Add coverage for 1632111

- tests/conftest.py
- tests/test_health.py
Fixes #98 
Test Results: 
```
$ pytest --ansible-host-pattern satellite --ansible-user=root --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_old_foreman_tasks
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.8.0, pluggy-0.6.0
ansible: 2.6.14
collected 20 items / 19 deselected                                                                                                                                                        
tests/test_health.py . …
```
> Fixes #98 - Test for old tasks in paused/stopped state.

- tests/test_health.py
- tests/test_upgrade.py
Test result:
```
$ pytest -sv --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_epel_repository 
collecting ... collected 21 items / 19 deselected
tests/test_health.py::test_positive_check_epel_repository 2020-06-23 18:21:40,856 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario
================================================================================
Check whether system don't have any non Red Hat repositories(Eg: EPEL) enabled: 
/ Checking repositories enabled on the system                         [FAIL]    
System is subscribed to non Red Hat repositories(Eg: EPEL) …
```
> Fix epel check related tests

- tests/test_advanced.py
- tests/test_health.py
- tests/test_packages.py
- tests/test_upgrade.py
Refs issue #177 - Run tests on capsule as well.
Tests added:
- test_positive_procedure_by_tag_check_migrations
- test_positive_procedure_by_tag_restore_confirmation
- test_positive_foreman_maintain_health_list
- test_positive_foreman_maintain_health_list_tags
- test_positive_list_health_check_by_tags
- test_positive_foreman_maintain_health_check
- test_positive_foreman_maintain_health_check_by_tags
- test_positive_pre_upgrade_health_check
- test_positive_check_upstream_repository
- test_positive_available_space
- test_positive_puppet_check_no_empty_cert_requests
- test_positive_puppet_check_empty_cert_requests
- test_positive_check_hotfix_installed
- test_positive_check_hotfix_installed_without_hotfix
- test_positive_check_yum_exclude_list
- …
> Issue #177 - capsule tests commit1

- tests/conftest.py
- tests/test_health.py
Refs: https://bugzilla.redhat.com/show_bug.cgi?id=1827176#c16
Test result:
```
(env-testfm) [jpathan@jpathan testfm]$ pytest -sv --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_tftp_storage 
platform linux -- Python 3.6.8, pytest-3.6.1, py-1.8.0, pluggy-0.6.0 -- /home/jpathan/projects/env-testfm/bin/python3
collecting ... collected 22 items / 21 deselected
tests/test_health.py::test_positive_check_tftp_storage 2020-09-11 15:30:08,376 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario …
```
> Fixes #179 - Add test for check-tftp-storage check

- tests/test_health.py
Refs: https://bugzilla.redhat.com/show_bug.cgi?id=1867753#c4 
Fixes #191 
Test result: 
```
$ pytest -sv --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_postgresql_checkpoint_segments 
platform linux -- Python 3.6.8, pytest-3.6.1, py-1.8.0, pluggy-0.6.0 -- /home/jpathan/projects/env-testfm/bin/python3
collecting ... collected 23 items / 22 deselected
tests/test_health.py::test_positive_check_postgresql_checkpoint_segments 2020-09-21 16:11:44,544 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario …
```
> Fixes #191 and #178 - Add test for check-postgresql-checkpoint-segments and env-proxy check.

- tests/test_advanced.py
- tests/test_backup.py
Test results:
```
$ pytest -sv --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_backup.py -k test_positive_backup_offline_all
collecting ... 0
0
collected 20 items / 19 deselected
PASSED
================== 1 passed, 19 deselected in 317.94 seconds ===================
```
```
$ pytest -sv --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_backup.py -k test_positive_backup_online_all
collecting ... 0
0
collected 20 items / 19 deselected
PASSED
================== 1 passed, 19 deselected in 240.71 seconds ===================
```
> Fix backup online/offline all tests

- tests/test_upgrade.py
**Satellite**:
```
(.testfm) [gtalreja@gtalreja testfm]$ pytest -sv --ansible-host-pattern server --ansible-user=root --ansible-inventory testfm/inventory tests/test_upgrade.py::test_positive_foreman_maintain_upgrade_list --pdb
===================================================== test session starts =====================================================
platform linux -- Python 3.8.6, pytest-3.6.1, py-1.9.0, pluggy-0.6.0 -- /home/gtalreja/sat_workspace/testfm/.testfm/bin/python3
collected 1 item
tests/test_upgrade.py::test_positive_foreman_maintain_upgrade_list 0
2020-12-23 20:10:44,883 - testfm.log - INFO - Checking for new version of …
```
> Fix test test_positive_foreman_maintain_upgrade_list

- tests/test_health.py
**Description:**
1. Added stubbed test for [BZ-1847889](https://bugzilla.redhat.com/show_bug.cgi?id=1847889)
2. Fix test `test_positive_check_hotfix_installed` by replacing exit code for warning with 78, Changes from https://projects.theforeman.org/issues/29699
```
$ pytest --ansible-host-pattern server --ansible-user=root --ansible-inventory testfm/inventory tests/test_health.py::test_positive_check_hotfix_installed -sq
2021-01-04 14:46:58,928 - testfm.log - INFO - Running preparation steps required to run the next scenarios
================================================================================
Check whether system has any non Red Hat repositories (e.g.: EPEL) enabled:
[SKIPPED]
-------------------------------------------------------------------------------- …
```
> Add stubbed test for BZ-1847889

- tests/conftest.py
- tests/test_health.py
1. Pip 21.0 removes python2.7 support, installing `pexpect` from python3 
2. Teardown for the fixture `setup_install_pexpect`
3. Fix `test_positive_check_old_foreman_tasks`
> pip 21.0 removes python2.7 support, installing pexpect from python3

- tests/test_health.py
- tests/test_service.py
- tests/test_upgrade.py
```
$ pytest -sv --junit-xml=foreman-results.xml --ansible-host-pattern server --ansible-user root --ansible-inventory ../testfm/inventory test_health.py -k test_positive_available_space_candlepin
========================================================== test session starts ==========================================================
platform linux -- Python 3.7.7, pytest-3.6.1, py-1.10.0, pluggy-0.6.0 -- /home/gtalreja/sat_workspace/testfm/.testfm/bin/python
cachedir: ../.pytest_cache
collected 25 items / 24 deselected                                                                                                      
test_health.py::test_positive_available_space_candlepin …
```
> Add qe-test-coverage for BZ-1900575, 1905801 and 1886031

- tests/test_health.py
```
$ pytest -sv --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_health.py::test_positive_remove_job_file
========================================================================================================== test session starts ===========================================================================================================
platform linux -- Python 3.8.7, pytest-3.6.1, py-1.10.0, pluggy-0.6.0 -- /home/akjha/satelliteQE/testfm_env/bin/python
rootdir: /home/akjha/satelliteQE/testfm, inifile:
collected 1 item …
```
> qe_test_coverage bz1762302

- README.rst
- conf/testfm.sample.yaml
- docs/source/index.rst
- requirements.txt
- testfm/__init__.py
- testfm/constants.py
- testfm/helpers.py
- tests/conftest.py
**Description**:
1. Removing fabric requirement from TestFM.
2. Pytest option `-s` will not be needed to work around fabric config issues.
3. Removing `SERVER_HOSTNAME` setting, as it was used earlier by `fabric.Connection` method.
4. Updating fixture `setup_old_foreman_tasks` to use `ansible_module.shell` to run command, attaching test results.
5. Updating Documentation to use Dynaconf YAML's and to not use `-s` with pytest.
```$ pytest -v --ansible-host-pattern server --ansible-user=root --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_old_foreman_tasks
========================================================== test session starts ==========================================================
platform linux -- Python 3.8.7, pytest-3.6.1, …
```
> Remove fabric dependency from TestFM

- tests/test_health.py
```
pytest -v --disable-warnings --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_health.py -k test_negative_check_server_ping
========================================================== test session starts ==========================================================
platform linux -- Python 3.7.7, pytest-3.6.1, py-1.10.0, pluggy-0.6.0 -- /home/gtalreja/sat_workspace/testfm/.testfm/bin/python
plugins: ansible-2.2.4
collected 26 items / 25 deselected                                                                                                      
tests/test_health.py::test_negative_check_server_ping PASSED …
```
> Fix test test_negative_check_server_ping

- testfm/constants.py
- testfm/content.py
- tests/conftest.py
- tests/test_content.py
- tests/test_prep_6_10_upgrade.py
Just adding some sanity tests and support.
Test result:
```
(venv) [vsedmik@localhost testfm]$ pytest -sv --ansible-host-pattern server --ansible-user=root --ansible-inventory testfm/inventory tests/test_prep_6_10_upgrade.py::test_positive_prep_6_10_upgrade tests/test_content.py::test_positive_content_migrate
=================== test session starts ===================
platform linux -- Python 3.9.5, pytest-3.6.1, py-1.10.0, pluggy-0.6.0 -- /home/vsedmik/PycharmProjects/testfm/venv/bin/python
rootdir: /home/vsedmik/PycharmProjects/testfm, inifile:
collected 2 items …
```
> Adding support and tests for pulp3 migration related subcommands.

- Dockerfile
Some dependencies don't have wheels on pypi
> Add python3-wheel to the Dockerfile

- tests/conftest.py
**Test Results**
```
1) pytest -v --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_maintenance_mode.py -k test_positive_maintenance_mode
=============================test session starts =========================================
collected 1 item                                                                                                                                                                                                                          
tests/test_maintenance_mode.py::test_positive_maintenance_mode …
```
> Test fix in sync_plan related tests

- tests/test_backup.py
Fix for #241
These files are expected inside the backup folder:
```
ONLINE:
With pulp: ['candlepin.dump', 'config_files.tar.gz', '.config.snar', 'foreman.dump', 'metadata.yml', 'pg_globals.dump', 'pulpcore.dump', 'pulp_data.tar', '.pulp.snar']
Skip pulp: ['candlepin.dump', 'config_files.tar.gz', '.config.snar', 'foreman.dump', 'metadata.yml', 'pg_globals.dump', 'pulpcore.dump']
OFFLINE:
With pulp: ['config_files.tar.gz', '.config.snar', 'metadata.yml', 'pgsql_data.tar.gz', '.postgres.snar', 'pulp_data.tar', '.pulp.snar']
Skip pulp: ['config_files.tar.gz', '.config.snar', 'metadata.yml', 'pgsql_data.tar.gz', '.postgres.snar']
```
Test results against Satellite 6.10.0 snap 20:
```
(venv) [vsedmik@localhost testfm]$ pytest -s --ansible-host-pattern server --ansible-user=root …
```
> Fix expected files for backup

- tests/conftest.py
- tests/test_health.py
**Satellite:**
```
$ pytest -v --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_non_rh_packages
=============================================================== test session starts ===============================================================
platform linux -- Python 3.8.2, pytest-3.6.1, py-1.10.0, pluggy-0.6.0 -- /home/gtalreja/sat_workspace/testfm/.testfm/bin/python3.8
plugins: ansible-2.2.4
collected 27 items / 26 deselected                                                                                                                
tests/test_health.py::test_positive_check_non_rh_packages PASSED …
```
> Add test for BZ-1869865

- tests/conftest.py
- tests/test_advanced.py
```
$  pytest -v --ansible-host-pattern server --ansible-user=root --ansible-inventory testfm/inventory tests/test_advanced.py -k test_positive_foreman_maintain_hammer_setup
========================================= test session starts ================================================
collected 14 items / 13 deselected …
```
> Fix test test_positive_foreman_maintain_hammer_setup

- testfm/constants.py
- tests/test_advanced.py
**Satellite:**
```
$ pytest -v --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_advanced.py -k test_positive_satellite_repositories_setup
============================================== test session starts ========================================================
collected 14 items / 13 deselected …
```
> Fix tests related to repositories setup

- tests/test_advanced.py
```
$ pytest -v --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_advanced.py -k test_positive_foreman_maintain_hammer_setup
===============================================test session starts =====================================================
collected 14 items / 13 deselected …
```
> Test fix related to hammer setup

- tests/conftest.py
- tests/test_service.py
```
$ pytest -v --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_service.py -k test_positive_foreman_maintain_service_status_bz1945916
============================================ test session starts =========================================================
collected 11 items / 10 deselected …
```
> Add test for BZ-1945916

- tests/test_health.py
- tests/test_packages.py
```
$ pytest -v --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_postgresql_checkpoint_segments
=============================================== test session starts =====================================================
collected 29 items / 28 deselected …
```
> Add manual tests and test scenario for BZ-1894149

- tests/conftest.py
```
$ pytest -v --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_corrupted_roles
=========================================== test session starts ================================================================
collected 29 items / 28 deselected                                                                                                                                                                                
tests/test_health.py::test_positive_corrupted_roles PASSED …
```
> Test fix for corrupted-roles check

- .github/workflows/merge_to_610z.yml
- .github/workflows/pull_request.yml
> Fix GHA to push 6.10.z, run GHA against Py3.8 and Py3.9

- tests/conftest.py
The minimum supported version for get-pip is updated to python3.7, and both el7 and el8 have the default python3 version as 3.6, so instead of changing the URL for a get-pip script, proposing changing the installation method using the python3 command.
> Change pip installation method for setup_install_pexpect

- tests/test_advanced.py
Missed here https://github.com/SatelliteQE/testfm/pull/273/files
**Tests Results:**
```
$ pytest -q --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_advanced.py -k test_positive_satellite_repositories_setup
.                                                                                                                                 [100%]
1 passed, 13 deselected in 800.01 seconds
```
> Remove 6.7 from test_positive_satellite_repositories_setup

- conf/testfm.sample.yaml
- testfm/__init__.py
- testfm/constants.py
HOTFIX_URL is the only setting available in testfm.yaml, which uses @jameerpathan111 FTP to download hotfix-package
@shubhamsg199 Added and deployed hotfix-package package on fedorapeople-fixtures container https://github.com/SatelliteQE/fedorapeople-repos/pull/11 , so moving to use it instead of personal FTP.
**Tests Results:** 
```
(.testfm) ➜  testfm git:(master) ✗ pytest -q --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_hotfix_installed
..                                                                                                                                                        [100%]
2 passed, 27 deselected in 441.96 seconds
```
Dependent MR for satelliteqe-jenkins: MR#524
Signed-off-by: …
> Remove HOTFIX_URL setting and use REPOS_HOSTING_URL instead

- conf/testfm.sample.yaml
- testfm/__init__.py
- testfm/constants.py
> [6.10.z] Remove HOTFIX_URL setting and use REPOS_HOSTING_URL instead

- tests/conftest.py
Backport of PR https://github.com/SatelliteQE/testfm/pull/274
> [6.9.z] Change pip installation method for setup_install_pexpect

- testfm/helpers.py
- tests/conftest.py
**`Test Results:`**
```
$ pytest -v --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_hotfix_installed
============================================ test session starts =============================================
collected 29 items / 27 deselected …
```
> [6.10.z]Fix hotfix tests

- testfm/constants.py
- testfm/helpers.py
- tests/conftest.py
```
$ pytest -k test_positive_check_hotfix_installed -v --ansible-host-pattern server --ansible-user=root  --ansible-inventory testfm/inventory
========================================== test session starts =============================================
collected 86 items / 84 deselected …
```
> Fix hotfix related tests for RHEL8

- README.rst
- docs/source/api/conf.py
- docs/source/conf.py
- setup.py
- testfm/advanced.py
- testfm/advanced_by_tag.py
- testfm/backup.py
- testfm/base.py
- testfm/constants.py
- testfm/content.py
- testfm/factory.py
- testfm/health.py
- testfm/maintenance_mode.py
- testfm/packages.py
- testfm/restore.py
- testfm/service.py
- testfm/upgrade.py
- tests/conftest.py
- tests/test_advanced.py
- tests/test_backup.py
- tests/test_health.py
- tests/test_maintenance_mode.py
- tests/test_packages.py
- tests/test_restore.py
- tests/test_service.py
- tests/test_upgrade.py
we should use downstream name
it is just symlink
```
ls -l /usr/bin/satellite-maintain
....  /usr/bin/satellite-maintain -> /usr/bin/foreman-maintain
```
> foreman maintain to satellite maintain

- tests/conftest.py
- tests/test_health.py
**`Test Results:`**
**RHEL7:**
```
$ pytest -v --ansible-host-pattern server --ansible-user=root --ansible-inventory testfm/inventory -k test_positive_check_duplicate_permissions tests/test_health.py
========================================== test session starts =======================================================================
collected 30 items / 29 deselected …
```
> Add check for duplicate permissions(BZ#1849110)

- .env.example
- .gitignore
- Makefile
- requirements.txt
- scripts/vault_login.py
- testfm/__init__.py
**Tests Results:**
```
(.testfm_vault) ➜  testfm git:(vault-integration) ✗ pytest -v --disable-warnings --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_satellite_maintain_health_list
====================================================================== test session starts =======================================================================
platform darwin -- Python 3.8.10, pytest-3.6.1, py-1.11.0, pluggy-0.6.0 -- /Users/gtalreja/sat_workspace/testfm/.testfm_vault/bin/python
rootdir: /Users/gtalreja/sat_workspace/testfm, inifile:
plugins: ansible-2.2.4
collected 30 items / 28 deselected
tests/test_health.py::test_positive_satellite_maintain_health_list PASSED …
```
> Vault integration to access secrets via DynaConf

- tests/test_health.py
**Descriptions:**
With recent change in 6.11 by [BZ 2048986](https://bugzilla.redhat.com/show_bug.cgi?id=2048986) removed the `clean_requirements_on_remove` parameter from the `validate-yum-config` check, this means the tests do not require this parameter to be asserted, thus it no longer requires an additional check.'
```
(.testfm) ➜  testfm git:(remove-clean-req) ✗ pytest -v --disable-warnings --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_validate_yum_config
====================================================================== test session starts =======================================================================
platform darwin -- Python 3.8.10, pytest-3.6.1, py-1.11.0, …
```
> Update validate-yum-config check test for BZ 2048986

- testfm/helpers.py
**Problem:**
A current approach to fetch versions using `product()` helper returns versions like `6.1` for 6.10.z and 6.11.z which caused a few tests to fail in automation
**Solution:**
```
In [1]: from testfm import settings
In [2]: from testfm.helpers import product
In [3]: settings.server.version.release
Out[3]: '6.11.0'
In [4]: product()
Out[4]: '6.11'
In [5]: settings.set("server.version.release", "6.10.6")
In [6]: settings.server.version.release
Out[6]: '6.10.6'
In [7]: product()
Out[7]: '6.10'
```
```
(.testfm) ➜  testfm git:(master) ✗ pytest -q --disable-warnings --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_upgrade.py -k test_positive_repositories_validate
. …
```
> Refactor product helper to read from dynaconf

- requirements.txt
- testfm/constants.py
- tests/test_advanced.py
**Tests Results:**
```
(.testfm) ➜  testfm git:(remove-ansible-el8) ✗ pytest -q --disable-pytest-warnings --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_advanced.py -k test_positive_satellite_repositories_setup
.                                                                                                                                                                     [100%]
1 passed, 13 deselected in 189.68 seconds
```
```
(.testfm) ➜  testfm git:(remove-ansible-el8) ✗ pytest -q -m capsule --disable-pytest-warnings --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_advanced.py -k test_positive_capsule_repositories_setup
. …
```
> Fix repo setup tests for missing maintain beta and not required ansible repo for el8
